### ISSUE TITLE
Fix FC in Settings > Additional settings > Button and gesture shortcuts

### ISSUE THREAD

**Issue by tmladenov** [ingbrzy/MA-XML-9.0-BULGARIAN-Global#1]
The items in string-array name="key_and_gesture_shortcut_action" are translated. Please delete that array in arrays.xml in Settings.apk.
![photo_2017-10-22_13-00-39](https://user-images.githubusercontent.com/5512397/31860793-154c1614-b729-11e7-90f2-3850ae546b9c.jpg)

**Comment by ingbrzy** [comment]
solved https://github.com/ingbrzy/MA-XML-9.0-BULGARIAN-Global/commit/de581de091643c937a96658df09ca553b3a9a4ee
